### PR TITLE
Allow search pin by name and cid

### LINKED ISSUE #2024: Allow search/filtering by pin name or cid
The search should be:
- calling the `list` from the api, with partial match, when what is types isn't a cid.
- calling the `list` by cid if what is typed looks like a cid (with can use the `isCid` helper)

### PR DESCRIPTION
**Pull request by Tbaut**
closes #2024

https://user-images.githubusercontent.com/33178835/160149854-1f4c7a1d-86eb-4516-9c51-db315a869453.mp4

### CODE REVIEW

**Comment by Tbaut** [comment]
added a small fix as we go, to avoid an overlap with the search icon (not visible in the video above)
image

**Comment by asnaith** [comment]
Looks great in the video, will check it out once the api is ready 😊

**Comment by Tbaut** [comment]
Hey all, this has been updated, feel free to review

**Comment by asnaith** [comment]
This is working great. I just found two small issues 

- The search input does not accept a space character so you'd never actually be able to search for "cute cat" 😿

- The search filter stays applied when you navigate away (but the search input is cleared). This could be confusing if the last search yielded no results (see video). 

https://user-images.githubusercontent.com/3982665/160943999-5cc391f6-f649-4d22-a265-ca3ab0b8b3ea.mov

**Comment by Tbaut** [comment]
Thanks Andrew for the laser eyes, it's fixed now

**Review by FSM1 — APPROVED** [review]

**Review by FSM1 — APPROVED** [review]

**Comment by tanmoyAtb** [comment]
> Thanks Andrew for the laser eyes, it's fixed now

Just checked that the "name" field in Add pin also doesn't allow `spaces` in the name.

**Review by tanmoyAtb — APPROVED** [review]
Looks good,

Just found the `space` issue in the ADD PIN modal, the current implementation looks great.

**Comment by asnaith** [comment]
> > Thanks Andrew for the laser eyes, it's fixed now
> 
> Just checked that the "name" field in Add pin also doesn't allow `spaces` in the name.

@tanmoyAtb We have that fixed in another branch :) https://github.com/ChainSafe/ui-monorepo/pull/2048

**Comment by Tbaut** [comment]
ah that's where I have it. Well I fixed it here as well [21232f7](https://github.com/ChainSafe/ui-monorepo/pull/2046/commits/21232f730d3e4fd4c0a0b3d21d871d029e1e1792)

**Pull request merged**
