### PR TITLE
Hover, selected states for App navigation

### LINKED ISSUE #1678: [a11y nits] Use sufficient contrast color for hover/focus
This issue is a list of cosmetic nits to make our hover states more consistent and meet a11y standards.

### Changes requested

1. Currently, hover on sidebar item has this interaction:  
Screen Shot 2021-10-29 at 9 44 44 AM

suggested change: a gray[4] background highlight when sidebar item selected and hovered: 
Screen Shot 2021-10-26 at 7 34 1

2. Currently, rows in the file browser with the gray striped background don't show selection state when hovered over.
Suggested change: Make the hover row background the same shade as selected row background(gray[4]) 
Screen Shot 2021-10-29 at 9 50 34 AM

3. Currently no interaction exists when hovering menu items in settings. It would be nice to add some hover interaction here. I'd also suggest to bump up the contrast when settings menu is selected by increasing font size to body1, font weight to `600` and making the icon a bit bigger. 
Screen Shot 2021-10-29 at 9 45 39 AM

### PR DESCRIPTION
**Pull request by tanmoyAtb**
closes #1678

This issue is quite an old one. I made the changes in point 1,
However the requested changes in 2, 3 didn't feel like it was improving UX, I left them out. 
Let me know what you think if 2 or 3 are needed.

---
Submission checklist: 

   

#### Layout
- [x] Change looks good in the desktop web ui
- [x] Change looks good in the mobile web ui

#### Theme
- [x] Components / elements inspected in light mode
- [x] Components / elements inspected in dark mode

#### Billing
- [x] Change applied to both files-ui and storage-ui

### CODE REVIEW

**Comment by asnaith** [comment]
> However the requested changes in 2, 3 didn't feel like it was improving UX, I left them out.
Let me what you think if 2 or 3 are needed.

I agree, doesn't seem necessary. 

Changes look great. Nice improvement to the mobile menu's especially. I thought they would use the same colour but this looks better. 

Screen Shot 2022-03-31 at 2 12 12 PM

**Review by asnaith — APPROVED** [review]

**Comment by Tbaut** [comment]
This is a bit conflicting with the design discussed here https://github.com/ChainSafe/ui-monorepo/issues/1284 but I think this looks cool too

**Comment by tanmoyAtb** [comment]
> This is a bit conflicting with the design discussed here #1284 but I think this looks cool too

Yup, I thought this version is more comfortable to the eyes.

**Review by Tbaut — APPROVED** [review]
nice!

**Pull request merged**
