### PR TITLE
Folders drag and drop

### LINKED ISSUE #959: Select and drag works for files, not for folders
Not sure if this is supposed to be that way, or if it's a bug (could be linked to https://github.com/ChainSafe/files-ui/pull/896 ?)
In any case as a user I was surprised that one type works and not the other.

ps: I will test in prod as soon as I can to tell if it's a regression or not

### PR DESCRIPTION
**Pull request by tanmoyAtb**
closes #959

### CODE REVIEW

**Comment by asnaith** [comment]
Nice. This is working really well for the most part. 

Preventing a folder from being moved into itself is working but I did notice if a folder is already in the root directory you can still move it to home (same for DND files too but I didn't notice this before). 

https://user-images.githubusercontent.com/3982665/149205053-2c4ecbb4-a6e7-49cd-bba6-19ceac33389d.mov

**Review by FSM1 — APPROVED** [review]
working great :)

**Comment by FSM1** [comment]
> Nice. This is working really well for the most part.
> 
> Preventing a folder from being moved into itself is working but I did notice if a folder is already in the root directory you can still move it to home (same for DND files too but I didn't notice this before).
> 
>  folder.moving.in.root.mov

@asnaith the bug you described actually relates to the work completed for #1836. I will create a separate issue to have this resolved.

**Review by asnaith — APPROVED** [review]
>>@asnaith the bug you described actually relates to the work completed for #1836. I will create a separate issue to have this resolved.

@FSM1 Ok, sounds good 👍

**Pull request merged**
