### PR TITLE
Release - 2022-04-04

### PR DESCRIPTION
**Pull request by FSM1**

### CODE REVIEW

**Review by Tbaut — APPROVED** [review]
blind approval based on the branch name
 :)

**Review by tanmoyAtb — APPROVED** [review]
The commits looks good :)

**Comment by asnaith** [comment]
The tests look good I can log into normal prod and stage sites but I'm having an issue signing in on both files and storage render links. 

Perhaps this is a configuration issue rather than true CORS issue?

Screen Shot 2022-04-04 at 10 22 49 AM

**Comment by FSM1** [comment]
> The tests look good I can log into normal prod and stage sites but I'm having an issue signing in on both files and storage render links.
> 
> Perhaps this is a configuration issue rather than true CORS issue?
> 
> Screen Shot 2022-04-04 at 10 22 49 AM

Since we do not have a pre-determined URL for the render link and we can't add these dynamically to the CORS allowed list for the PROD api (which the Prod release PR previews are pointed at). The CORS errors here are entirely expected

**Comment by asnaith** [comment]
> > The tests look good I can log into normal prod and stage sites but I'm having an issue signing in on both files and storage render links.
> > Perhaps this is a configuration issue rather than true CORS issue?
> > Screen Shot 2022-04-04 at 10 22 49 AM
> 
> Since we do not have a pre-determined URL for the render link, we can't add these dynamically to the CORS allowed list for the PROD api (which the PR previews are pointed at. The CORS errors here are entirely expected.

Thanks for clarifying @FSM1. I usually review the commits manually to make sure I'm familiar with all the changes then review the automated test results but this time I wanted to sign-in due to other issues we'd seen in stage last week...but as soon as I read your message I remembered we've never been able to do this on prod / render. Brb need more coffee 😄. 

We're good to go with this then 🚀

**Review by asnaith — APPROVED** [review]

**Pull request merged**
