### PR TITLE
Release - 2022-07-01

### PR DESCRIPTION
**Pull request by FSM1**

### CODE REVIEW

**Comment by juans-chainsafe** [comment]
Seems good to me, tried locally to review the changes!

**Review by Tbaut — APPROVED** [review]
:+1:

**Review by tanmoyAtb — APPROVED** [review]

**Comment by Tbaut** [comment]
Codacy failing is nothing to be worry of BTW

> KubernetesDockerRunner: Container for codacy/codacy-eslint:9.1.137 exited with non-zero code 1
Error: Failed to load plugin 'ternary' declared in '.eslintrc.json': Cannot find module 'eslint-plugin-ternary'
Require stack:

**Comment by FSM1** [comment]
> Codacy failing is nothing to be worry of BTW
> 
> > KubernetesDockerRunner: Container for codacy/codacy-eslint:9.1.137 exited with non-zero code 1
> > Error: Failed to load plugin 'ternary' declared in '.eslintrc.json': Cannot find module 'eslint-plugin-ternary'
> > Require stack:

ahhh nice catch, I was wondering about that...

**Pull request merged**
