### PR TITLE
[Files] Breadcrumb enhancement for shared folders

### LINKED ISSUE #1284: Breadcrumb for shared folders should start at the overview
Edit: look at the [last post](https://github.com/ChainSafe/ui-monorepo/issues/1284#issuecomment-1087777710) in this conversation, this is what we want to have.

---
I find it difficult to know whether I'm in a shared folder or if I'm in my home. Ping @sweetpea22 
I'd like to suggest some changes:

- different colors for the root shared folder
- different color for the breadcrumb to know right away?
- the shared folder at the root instead of the home

image
image

### PR DESCRIPTION
**Pull request by Tbaut**
closes #1284

---
Submission checklist: 

   

#### Layout
- [x] Change looks good in the desktop web ui
- [x] Change looks good in the mobile web ui

#### Theme
- [x] Components / elements inspected in light mode
- [x] Components / elements inspected in dark mode

### CODE REVIEW

**Comment by Tbaut** [comment]
Tests failing is unrelated, I opened #2198 
Also the SVG is not nice in the Breadcrumb for shared folders, but we'll get this fixed before merging.
image


edit: fixed

**Review by juans-chainsafe — CHANGES_REQUESTED** [review]
EDIT: I put the review for other PR, my bad

**Comment by juans-chainsafe** [comment]
@Tbaut Looking good in Chrome! I need to test in other browsers too and mobile, but seems good so far. I only have one question:

If I understood correctly, based on https://github.com/ChainSafe/ui-monorepo/issues/1284#issuecomment-1087777710 comment, the last folder name should be complete and not with elipsis:
 
Screen Shot 2022-06-21 at 15 36 54

Maybe we need more clarification there.

**Comment by Tbaut** [comment]
Ah I didn't take this into account here. I didn't touch this part and just went for the Breadcrumb enhancement for shared folders and the root. Any folder with a too long name will have ellipsis as before. I guess we can tackle that in another issue if that's really an issue (which I don't really think it is).

**Comment by juans-chainsafe** [comment]
> Ah I didn't take this into account here. I didn't touch this part and just went for the Breadcrumb enhancement for shared folders and the root. Any folder with a too long name will have ellipsis as before. I guess we can tackle that in another issue if that's really an issue (which I don't really think it is).

Yes, make sense, I can create another ticket and we can discuss it tomorrow

**Review by juans-chainsafe — CHANGES_REQUESTED** [review]
Functionality is working as expected in all browsers but we have an issue inside the dropdown menu in 'Manage access' option:
Screen Shot 2022-06-21 at 16 33 59

Seems that something happened in the design, in stage is displayed correctly.

**Comment by Tbaut** [comment]
Nice catch, this is an issue with the svg as well. Added a quick fix for this particular issue, but the svg still needs attention.

**Comment by Tbaut** [comment]
The icon is now fixed and it scales correctly :tada:

**Review by juans-chainsafe — APPROVED** [review]
all working perfect now! awesome

**Comment by tanmoyAtb** [comment]
Overall the code looks tight. 

I still feel the svgs and icons could get some improvement.

The storybooks icon looks big (not a big deal though)!
Screenshot 2022-06-24 at 12 37 42 AM

In files they look smaller that usual.
Screenshot 2022-06-24 at 12 38 54 AM

**Review by FSM1 — APPROVED** [review]
works great 🎉

**Comment by Tbaut** [comment]
> In files they look smaller that usual.

I missed that sorry. So the home icon should be 20px size, and this shouldn't have changed (in the app, I didn't check storybook).
The shared-folder group icon is new , we can make it more than 20px but this is what we had so far afaik.

**Pull request merged**
