### PR TITLE
Place user dropdown in app nav

### LINKED ISSUE #1647: User Dropdown restyle
- User menu moved to sidebar
- User Identicon as per the screenshot below, colored generatively (Can probably use the user's UUID for the seed data).
- Clicking on the item will open a menu allowing user to log out

See [figma](https://www.figma.com/file/wRMGqc11iQLVpDVmqXVXWK/ChainSafe-Files?node-id=4297%3A60807)

### PR DESCRIPTION
**Pull request by tanmoyAtb**
closes #1647

### CODE REVIEW

**Review by Tbaut — CHANGES_REQUESTED** [review]
Can the username be bigger? Also can we use the identicon library we were talking about, I believe it's this one https://github.com/emeraldpay/hashicon

**Comment by tanmoyAtb** [comment]
> Can the username be bigger? Also can we use the identicon library we were talking about, I believe it's this one https://github.com/emeraldpay/hashicon

Made the updates, Hashicon added, made some style updates

**Review by RyRy79261 — APPROVED** [review]

**Review by RyRy79261 — APPROVED** [review]

**Comment by Tbaut** [comment]
Hey @tanmoyAtb, it looks great, just the dropdown isn't properly centered I figured, there's a padding on the section
image

**Review by Tbaut — APPROVED** [review]
Happy to merge once this horizontal padding is removed.

**Review by FSM1 — APPROVED** [review]

**Pull request merged**
