### PR TITLE
[FILES] Fixed dark mode components

### LINKED ISSUE #1347: Files: Create / Copy To Shared Folder Modal elements do not match dark theme
**Screenshots**

Screen Shot 2021-07-26 at 8 54 36 PM

Screen Shot 2021-07-26 at 9 07 02 PM

### PR DESCRIPTION
**Pull request by RyRy79261**
closes #1347

### CODE REVIEW

**Comment by asnaith** [comment]
Hey Ryan, just built this locally to check it out (render link for files wasn't working for me). I noticed a few minor things: 

- On the "Copy to shared folder" modal the background to the label is not the same as the modal body

Screen Shot 2021-07-27 at 3 49 39 PM

- The body colour of the "Create Shared Folder" seems to be a darker shade than the other modals that we use in the app. 

- The animation of the dropdown arrow is a bit more noticeable now in dark mode, you can see that it's a rotating square image (just wanted to mention in case it's not supposed to be like this, I'm not 100% sure). 

https://user-images.githubusercontent.com/3982665/127239437-e8da1574-ffeb-4294-8ce2-2684504aa1f3.mov

**Comment by RyRy79261** [comment]
Nice spots @asnaith 

Should be resolved neow

**Comment by FSM1** [comment]
image
The label background is still too dark, and the Dropdown selected value is barely visible

**Comment by asnaith** [comment]
Animation on the dropdown looking good now 👍 as is everything else is great except for the label backgrounds on both dialogs now. 

Screen Shot 2021-07-28 at 12 43 25 PM


Screen Shot 2021-07-28 at 12 44 49 PM

**Review by Tbaut — APPROVED** [review]
Looking dope thanks a ton

**Comment by asnaith** [comment]
Looks perfect now, thanks Ryan 😃

**Review by asnaith — APPROVED** [review]

**Review by tanmoyAtb — APPROVED** [review]

**Pull request merged**
