### PR TITLE
[Storage] Allow renaming a bucket

### LINKED ISSUE #2183: [Storage] Add ability to rename a Bucket
**Description**
I want to be able to rename an existing Bucket in Storage for type '**Chainsafe**' and '**IPFS**'

**Additional context**
Screen Shot 2022-06-10 at 10 33 44

### PR DESCRIPTION
**Pull request by Tbaut**
closes #2183

### CODE REVIEW

**Comment by Tbaut** [comment]
it's ready to go now that https://github.com/ChainSafe/files-api/issues/2380 is in.

**Review by juans-chainsafe — CHANGES_REQUESTED** [review]
Great work! main functionality is working perfect, but I found some issues:
When you try to rename the bucket with an empty input,the dialog box is cut off in the screen:
Screen Shot 2022-07-27 at 09 08 52
Based on renaming an empty folder/file I think the box should say: "A name is required."

The second error, is when you try to rename the bucket with a bucket name that already exists, basically nothing happens, I see in the https://stage-api.chainsafe.io/api/v1/buckets/fef85ff2-23b1-4b53-bbf6-c83c022938ba API response that throw the error '...[E11000 duplicate key error collection...' so we have 2 possible solutions here:
- Show an error message that can't be renamed with an existing name
- Do the same that we do when renaming a folder: add '(1)' (or the corresponding number) at the end of the bucket name

**Comment by Tbaut** [comment]
> The second error, is when you try to rename the bucket with a bucket name that already exists, basically nothing happens, I see in the https://stage-api.chainsafe.io/api/v1/buckets/fef85ff2-23b1-4b53-bbf6-c83c022938ba API response that throw the error '...[E11000 duplicate key error collection...' so we have 2 possible solutions here:

Ah thanks for testing it, this is something that should be handled on the api level. I opened https://github.com/ChainSafe/files-api/issues/2500

I'll fix the other issue with the error

**Comment by Tbaut** [comment]
The error message overflow is fixed now thanks for checking this out

**Review by juans-chainsafe — APPROVED** [review]
Design error in the dialog box was fixed! 
So, everything doable in the UI is done, so I will approve it and check again the 'rename with existing name' when the API tickets is closed.

**Review by tanmoyAtb — APPROVED** [review]
Looks good to go!

**Pull request merged**
