### PR TITLE
Text Input Icon Cursor

### LINKED ISSUE #1274: ChainSafe Storage: Clear button on Pin Cid modal highlights text instead of clearing
**Description**
The clear input button (displayed on the Pin Cid modal after an error) when clicked will highlight text instead of clearing it

**Steps to Reproduce**
1. Login to Storage
2. Click the "Pin cid" button
3. Enter an invalid name to invoke a "CID Invalid" error
4. Click the cross icon that appears on the input box

**Observed behavior**
After clicking the cross icon the text is selected and not cleared

**Expected behavior**
After clicking the cross icon the text should be cleared

**Screenshots**
Screen Shot 2021-07-14 at 2 09 24 PM

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox
 - Version : 89.02

### PR DESCRIPTION
**Pull request by FSM1**
Closes #1274

### CODE REVIEW

**Review by Tbaut — APPROVED** [review]

**Comment by asnaith** [comment]
I can still reproduce the original bug on the Render link for the PR. Clicking the icon is not clearing the input. 

https://user-images.githubusercontent.com/3982665/125983278-2e1eeaf5-5345-42df-8d50-de45d306a33c.mov

**Comment by Tbaut** [comment]
So the thing is, this red cross only tells there's an error, it's not meant to be a "clear" button, hence the "solution" being making sure there's no cursor: pointer like you would have for a button. So the original issue isn't actually a real bug, it's more a UX problem.

**Comment by asnaith** [comment]
@Tbaut Oh ok, good to know! Thanks for explaining.

**Review by asnaith — APPROVED** [review]

**Review by tanmoyAtb — APPROVED** [review]
💯

**Pull request merged**
