### PR TITLE
Cookie banner styling

### LINKED ISSUE #1845: Cookie notification overlapping
image

### PR DESCRIPTION
**Pull request by tanmoyAtb**
closes #1845

---
Submission checklist: 

   

#### Layout
- [x] Change looks good in the desktop web ui
- [x] Change looks good in the mobile web ui

#### Theme
- [x] Components / elements inspected in light mode 
- [x] Components / elements inspected in dark mode

### CODE REVIEW

**Review by Tbaut — APPROVED** [review]
:100:

**Comment by asnaith** [comment]
Oops, I couldn't work out how to test this 🤦‍♂️ 

Cleared my browser, tried editing local storage etc but could not get it to show. Any tips?

**Comment by Tbaut** [comment]
Showing the banner is quite a long process, where it first checks that the posthog is initialized etc. This is something we don't have in render to prevent having our tests in the analytics. The easiest to test it would then be to edit the code here https://github.com/ChainSafe/ui-monorepo/blob/dev/packages/files-ui/src/Contexts/PosthogContext.tsx#L97 and make sure you're in a private tab.

**Comment by FSM1** [comment]
> Showing the banner is quite a long process, where it first checks that the posthog is initialized etc. This is something we don't have in render to prevent having our tests in the analytics. The easiest to test it would then be to edit the code here https://github.com/ChainSafe/ui-monorepo/blob/dev/packages/files-ui/src/Contexts/PosthogContext.tsx#L97 and make sure you're in a private tab.

Managed to successfully test this on local by adding the necessary ENV variables:
```
REACT_APP_POSTHOG_PROJECT_API_KEY=phc_aHikZYLRMFBEPbBokafenhasCyfS7YSalx7rgsHwfXR
REACT_APP_POSTHOG_INSTANCE_ADDRESS=https://posthog.chainsafe.io
```

image

**Review by FSM1 — APPROVED** [review]

**Pull request merged**
