### PR TITLE
Fix video preview overflow

### LINKED ISSUE #1681: Content Preview: Portrait Videos Not Sized to Window (Mobile)
When previewing a portrait-shot video while in landscape orientation, the video is not properly sized.

https://images.zenhubusercontent.com/285884697/2fedc9bd-eed3-4f88-8295-98b6c8a9d78c/vertical_video_preview_in_landscape__mobile_.mp4

**Suggested Solutions:**
Automatically resizing videos no matter which orientation on mobile.

### PR DESCRIPTION
**Pull request by FSM1**
Closes #1681

### CODE REVIEW

**Review by tanmoyAtb — COMMENTED** [review]
💯

**Review by tanmoyAtb — APPROVED** [review]

**Comment by asnaith** [comment]
On iOS no video will display now in Safari (portrait or landscape). 

It shows the loading progress bar and then shows the empty preview like in the screenshot below: 

image

image

I checked stage and there's no problem displaying landscape videos (only the original issue).

**Comment by FSM1** [comment]
> On iOS no video will display now in Safari (portrait or landscape).
> 
> It shows the loading progress bar and then shows the empty preview like in the screenshot below:

Ahhh nooo... ok, I will have to do a bit more research into how to handle this. @RyRy79261 any ideas from your side?

Does the video display correctly with these changes in Safari on OSX?

**Comment by asnaith** [comment]
> > On iOS no video will display now in Safari (portrait or landscape).
> > It shows the loading progress bar and then shows the empty preview like in the screenshot below:
> 
> Ahhh nooo... ok, I will have to do a bit more research into how to handle this. @RyRy79261 any ideas from your side?
> 
> Does the video display correctly with these changes in Safari on OSX?

@FSM1 Yeah, it is displaying correctly within Safari on macOS (desktop and mobile layout).

**Comment by asnaith** [comment]
I just realised that on iOS the preview is broken for all file types on this branch, not just movies. Not sure if that makes the issue easier to deduce. 

https://user-images.githubusercontent.com/3982665/142077835-0546348a-2413-441b-8fd5-b22cc9bfd354.MOV

**Comment by FSM1** [comment]
> I just realised that on iOS the preview is broken for all file types on this branch, not just movies. Not sure if that makes the issue easier to deduce.

Hmmm, nope that only makes it weirder. The changes on this branch only modified the CSS for the video preview, so there should ne no changes to any of the other file-types 🤷🏼

**Review by RyRy79261 — APPROVED** [review]

**Comment by asnaith** [comment]
@FSM1 So....the issue with no content appearing seems to be between my localhost and device! I hope you didn't burn too much time on this. 

Originally I was testing against localhost because the render link was giving me a 404. However, the pr render link is working now and when I  re-tested it on via there it works perfectly - All file types, all device rotations, all video styles etc.

I even switched back to localhost and can still see the same issue as before happening, 100% reproducible. Obviously, not something related to this code change though and I don't know what's happening as there are no dev tools on iOS!

Looking as expected on render: 

IMG_3123 2

**Review by asnaith — APPROVED** [review]

**Pull request merged**
