### PR TITLE
Header buttons and icons alignments

### LINKED ISSUE #1663: New Folder button icon not responsive
Inside a shared folder, the **New folder** button has an unresponsive icon that shrinks when window is resized.

In addition, when the two buttons combine into a single menu the name for it changes from **New folder** to **Create folder**. This issue is the same across all of the pages (Home, Shared, etc.).

_Suggested solutions:_
Make the icon responsive, and keep the name consistent by using **New folder** in all menu's.

### PR DESCRIPTION
**Pull request by tanmoyAtb**
closes #1663 

Added ellipsis and word wraps to the header to keep things aligned.

### CODE REVIEW

**Review by RyRy79261 — APPROVED** [review]

**Review by Tbaut — CHANGES_REQUESTED** [review]
The button to add a shared folder still has the icon that scales and becomes weirdly small

image

**Comment by tanmoyAtb** [comment]
> The button to add a shared folder still has the icon that scales and becomes weirdly small
> 
> image

Thanks for pointing that out, Made the updates

**Review by FSM1 — CHANGES_REQUESTED** [review]
Just the mobile dropdown text that needs to be updated
image

**Comment by tanmoyAtb** [comment]
> Just the mobile dropdown text that needs to be updated image

All updated

**Review by FSM1 — APPROVED** [review]

**Review by asnaith — APPROVED** [review]
Nice improvement :)

**Review by Tbaut — APPROVED** [review]
:100:

**Pull request merged**
