### PR TITLE
Cross position in subscription modal fix

### PR DESCRIPTION
**Pull request by tanmoyAtb**
We had a small bug on the subscription modal with some screen sizes. Here's a screenshot.

Screenshot 2022-02-11 at 8 48 28 PM

This PR fixes the problem.

### CODE REVIEW

**Review by Tbaut — COMMENTED** [review]
Nice, while we're here, I noticed there's the same css used in `PayInvoiceModal.tsx` with the same bug, fixed by the same 480 instead of `undefined`, can you add it there too?

**Comment by FSM1** [comment]
This change does mess with the padding that the modal usually has:
Before:
image

After:
image

**Comment by asnaith** [comment]
Looks good 🔥

I will re-test when crypto payment modal gets the same fix applied

**Comment by tanmoyAtb** [comment]
All right, this should be good now. 👍

**Review by asnaith — APPROVED** [review]

**Comment by Tbaut** [comment]
I'll let @FSM1 confirm it's looking good

**Review by FSM1 — APPROVED** [review]
Works well 🎉

**Pull request merged**
