### PR TITLE
[Files] - Don't show any success message when there's an error

### LINKED ISSUE #1336: Both an error and a success message displayed after sharing
Reported by @sadiq1971 

You end up with an error and a success message.
Would you mind adding any more info you have?

image

### PR DESCRIPTION
**Pull request by Tbaut**
closes #1336

### CODE REVIEW

**Review by FSM1 — APPROVED** [review]

**Comment by asnaith** [comment]
I followed the original reproduction steps mentioned by @sadiq1971 and it looks like there's still an issue. We're not displaying the error on the dialog anymore but we are still showing the modal stating the copy action was successful when it wasn't. 


https://user-images.githubusercontent.com/3982665/127394739-470739b1-9c2a-4dd2-a5ee-f95acea914b7.mov

**Comment by Tbaut** [comment]
Thanks for checking this out. This is a different problem. What you demoed is for upload, his issue was for download which should now be solved. I'll check it out and make sure a proper error is shown. Also we should probably remove the notifications in the background and rather show some info in the modal. It's not trivial so I willingly left this for a later issue.

**Review by RyRy79261 — APPROVED** [review]

**Comment by Tbaut** [comment]
Should be good, a video of both DL and upload errors. Please merge @asnaith if that's looking good for you.

https://user-images.githubusercontent.com/33178835/127503524-2cc50cbd-9cd5-440e-899c-64104d46a554.mp4

**Comment by asnaith** [comment]
@Tbaut Awesome, looks great now 😃

**Pull request merged**
