### PR TITLE
Disable IPFS MFS filesystem creation

### PR DESCRIPTION
**Pull request by FSM1**
Submission checklist: 

#### Layout
- [x] Change looks good in the desktop web ui
- [x] Change looks good in the mobile web ui

#### Theme
- [x] Components / elements inspected in light mode
- [x] Components / elements inspected in dark mode

### CODE REVIEW

**Comment by juans-chainsafe** [comment]
@FSM1 Hi! what need to be tested here? do we have a ticket for this with more information?

**Comment by FSM1** [comment]
> @FSM1 Hi! what need to be tested here? do we have a ticket for this with more information?

Unfortunately there is not a ticket for this change. Due to the performance issues with the IPFS (MFS) filesystem, we have taken a decision to disable this bucket type from creation. I see there are some storage tests failing, which I will go through and make sure that none of the tests depend on this file-system type.

**Review by tanmoyAtb — APPROVED** [review]
For the purpose at hand, looks good !

**Comment by juans-chainsafe** [comment]
@FSM1 got it! I checked the UI and is ok, buuut I saw that you only commented one IPFS test, but we have a lot more, the thing on the others, is that they create an IPFS buckets using the API, so they are able to create the bucket and the tests passed. All of this in bucket-management.cy.ts I can comment those test as well if you want, but again, they are not failing because they use the API to create the ipfs bucket

**Comment by FSM1** [comment]
> others, is that they create an IPFS buckets using the API, so they are able to create the bucket and the tests passed. All of this in bucket-management.cy.ts I can comment those test as well if you want, but again, they are not failing because they use the API to create the ipfs bucket

Im happy to have all those tests commented out for now.

**Comment by juans-chainsafe** [comment]
> > others, is that they create an IPFS buckets using the API, so they are able to create the bucket and the tests passed. All of this in bucket-management.cy.ts I can comment those test as well if you want, but again, they are not failing because they use the API to create the ipfs bucket
> 
> Im happy to have all those tests commented out for now.

Done! tests related to IPFS were commented

**Review by juans-chainsafe — APPROVED** [review]

**Pull request merged**
