### PR TITLE
Focus colors on buttons

### LINKED ISSUE #1964: Focus state on buttons in the preview in dark mode make the button invisible
from https://github.com/ChainSafe/ui-monorepo/pull/1960#pullrequestreview-888584444

In dark mode, click on some buttons. When they are active, they aren't visible
image

https://user-images.githubusercontent.com/33178835/154969151-2a873d0c-9e61-4f15-a817-cdd5d2624ce0.mp4

Add more contrast for the colors in dark mode

### PR DESCRIPTION
**Pull request by tanmoyAtb**
closes #1964 

Checked over the focus and active states of all the variant of the buttons, Please go through the UI and see everything feels natural.

---
Submission checklist: 

   

#### Layout
- [x] Change looks good in the desktop web ui
- [x] Change looks good in the mobile web ui

#### Theme
- [x] Components / elements inspected in light mode 
- [x] Components / elements inspected in dark mode

### CODE REVIEW

**Comment by Tbaut** [comment]
I checked quickly the arrow of the preview, and still have the problem mentioned here (the video) that the arrow is barely visible: https://github.com/ChainSafe/ui-monorepo/issues/1964

**Comment by tanmoyAtb** [comment]
This is what I see now. 
Screenshot 2022-02-25 at 11 27 06 PM
Screenshot 2022-02-25 at 11 26 58 PM

Only way to make this more visible is to have a whitish border or whitish background button.

**Comment by tanmoyAtb** [comment]
All right, I've made updates to the preview controls
Screenshot 2022-02-26 at 12 09 00 AM

**Review by asnaith — APPROVED** [review]

**Review by Tbaut — APPROVED** [review]
Working well now, thanks!

**Pull request merged**
