### PR TITLE
Show information when there are no notifications

### LINKED ISSUE #1821: Nice notification image when there's nothing to show
It'd be great to have a nice little icon/drawing to show when there's no notifications to show to our users.

It doesn't have to be crazy, a simple icon as we have when there's no file to show is sufficient.
image

### PR DESCRIPTION
**Pull request by Tbaut**
closes #1821

TODO:
- [x] Add the image in high res , I used the bell icon for now

---
Submission checklist: 

   

#### Layout
- [x] Change looks good in the desktop web ui
- [x] Change looks good in the mobile web ui

#### Theme
- [x] Components / elements inspected in light mode 
- [x] Components / elements inspected in dark mode

### CODE REVIEW

**Comment by asnaith** [comment]
Working well. 

I thought the background colour of the notification area could perhaps be a little lighter, what do you think? I can see the shadow but its colour is quite close to the regular background (looks good on hover though). 

Screen Shot 2021-12-17 at 7 57 33 PM

**Review by tanmoyAtb — APPROVED** [review]
Looks good, other than the dark mode point ! would be good to get that in.

**Comment by Tbaut** [comment]
added the high res icon and some lighter background, it's looking better I think.
image
image

**Comment by tanmoyAtb** [comment]
> added the high res icon and some lighter background, it's looking better I think. image image

I would add some padding between the icon and the "There are no notifications" text.

**Comment by Tbaut** [comment]
here we go 
image

**Pull request merged**
