### PR TITLE
Right click on shared folder overview ans Storage bucket overview

### LINKED ISSUE #2153: Add right click menu to Shared folder and Bucket overview
The buckets overview in Storage and the Shared folder overview in Files do not have a right click menu yet.

### PR DESCRIPTION
**Pull request by Tbaut**
closes #2153

### CODE REVIEW

**Review by juans-chainsafe — COMMENTED** [review]
Looks good! the right click is working nice and clean.

I have a suggestion, maybe we can add a toast message when we delete a Shared folder or a Bucket to have the same behaviour that we have in Files in Home

**Comment by Tbaut** [comment]
yes I realized this as well, when testing, we need to add this. I'll create an issue for this since it's not related.

**Review by juans-chainsafe — APPROVED** [review]

**Review by tanmoyAtb — APPROVED** [review]
Looks like a clean implementation. working nicely.
Made me realise, we must add a "Confirmation dialogue" on storage before deleting buckets.
Deleting buckets is quite an impactful task.

**Comment by Tbaut** [comment]
Hehe yup, that's what Juan was saying, I created an issue :)

**Pull request merged**
