### PR TITLE
Style the error boundaries component

### LINKED ISSUE #41: Create a styled Error Fallback component
Currently the Error Boundary fallback component is hard-coded and unstyled. This should be updated to use the styling solution we are using for the remainder of the app. See `files-ui/src/app.tsx` for the current implementation.

### PR DESCRIPTION
**Pull request by Tbaut**
closes #41 ooooh that feels good!

I wasn't able to use `createStyle`, the app kept crashing, saying I wasn't able to use `useTheme`. so I did this all manually :man_shrugging:.

Edit: error boundaries are a weird kind of component based on old fashion classes where you can't use hooks basically https://blog.lookitskris.com/error-boundaries-hooks/

image
image

---
Submission checklist: 

   

#### Layout
- [x] Change looks good in the desktop web ui
- [x] Change looks good in the mobile web ui

#### Theme
- [x] Components / elements inspected in light mode 
- [x] Components / elements inspected in dark mode

### CODE REVIEW

**Comment by asnaith** [comment]
I ran this branch locally and temporarily reverted Tanmoy's search fix to test this out. Looking good in both themes. 

The close button was not responding to my click action and I also noticed that after around 6 seconds of being displayed the styling for the error disappears and the unstyled error is displayed. Video below: 

https://user-images.githubusercontent.com/3982665/152240861-ea121367-a076-48f8-9258-204890411afa.mov

**Comment by Tbaut** [comment]
What you see after some time is the react development error (which is still nice actually) because you run a dev server. This would not be shown in prod. or on render. The reason it is lagging is because this error is being prepared. Close it with the cross at the top right and you'll see the error boundaries component again, and the close button should then work.

**Comment by asnaith** [comment]
> What you see after some time is the react development error (which is still nice actually) because you run a dev server. This would not be shown in prod. or on render. The reason it is lagging is because this error is being prepared. Close it with the cross at the top right and you'll see the error boundaries component again, and the close button should then work. 

Sounds good 👍 thanks for the explanation. I wasn't sure what was happening there.

**Review by asnaith — APPROVED** [review]
Re-tested and closed the react development error, all is beautiful 🔥

**Comment by tanmoyAtb** [comment]
Its amazing how the light and dark theme `vars` worked out. 👍 

I'm not sure how useful the stack part of the modal would be. This is what I got on a local build version.

Screenshot 2022-02-04 at 11 54 29 PM

@asnaith thanks for giving the idea on how to best test this PR :)

**Comment by Tbaut** [comment]
Yeah, the stack can be useful, as well as useless, it'll really depend on the error itself!
In my case (and Andrew's as well) it's actually super helpful because we know which component the error is coming from, but it may be obscure in a build indeed..

**Review by FSM1 — APPROVED** [review]

**Pull request merged**
