### PR TITLE
UI layout adjustments and sticky bulk actions

### LINKED ISSUE #2052: With a long list of files on desktop the bulk actions should be sticky to the top of the screen
When you have a lot of files and select some, it's not immediately obvious that you have access to bulk actions on the top.
We should make sure that the bulk actions are visible and sticky at the top of the screen

### PR DESCRIPTION
**Pull request by tanmoyAtb**
closes #2052 

---
Submission checklist: 

   

#### Layout
- [x] Change looks good in the desktop web ui
- [x] Change looks good in the mobile web ui

#### Theme
- [x] Components / elements inspected in light mode
- [x] Components / elements inspected in dark mode

#### Storage
- [x] Change applied to both files-ui and storage-ui

### CODE REVIEW

**Comment by asnaith** [comment]
Nice improvement, looking good in Chrome and Safari. 

I know this is still a draft but I noticed a small quirk on Firefox where the container is no longer dimmed when the upload modal is in view: 

Screen Shot 2022-04-05 at 8 54 20 PM

**Comment by tanmoyAtb** [comment]
> Nice improvement, looking good in Chrome and Safari.
> 
> I know this is still a draft but I noticed a small quirk on Firefox where the container is no longer dimmed when the upload modal is in view:
> 
> Screen Shot 2022-04-05 at 8 54 20 PM

Great catch @asnaith , I surely would have missed this one.

**Comment by tanmoyAtb** [comment]
The overall changes has some effect on most of the page layouts, in storage and files.
Here's a preview of the sticky bulk actions.

https://user-images.githubusercontent.com/10713353/162034011-4848931b-0d6f-4e41-ba88-bd44affa9b39.mov

**Review by Tbaut — APPROVED** [review]
This is super slick!

**Review by asnaith — APPROVED** [review]
Looking great in firefox and for storage too

**Pull request merged**
