### PR TITLE
Enhance login screen with quicker email

### LINKED ISSUE #1209: New sign-in screen
- Input field and primary has been added so people can sign in with their emails faster.
- Web3 button used to be blue, now it's black
Capture d’écran 2021-06-30 à 11 26 17

### PR DESCRIPTION
**Pull request by Tbaut**
- closes #1209
- adds an ethereum logo
- slight change in the copy of the original design to make it less redundant with the "Continue" being repeated.

### CODE REVIEW

**Comment by Tbaut** [comment]
it's already a big enough one, I'll create other PRs for Gaming and Storage once this one is reviewed. It'll be mostly copy/paste, and that's where a lot of errors get introduced :see_no_evil:

**Review by tanmoyAtb — APPROVED** [review]
Works great! 👍

**Comment by asnaith** [comment]
Looking good on render. Really nice improvement to streamline the process. 

Liking the addition of the ethereum logo on the web3 button too!

**Review by asnaith — APPROVED** [review]

**Review by FSM1 — APPROVED** [review]
works great

**Pull request merged**
