### PR TITLE
[Storage] Fix login screen and nav bar

### PR DESCRIPTION
**Pull request by Tbaut**
One part of https://github.com/ChainSafe/ui-monorepo/issues/1968

https://user-images.githubusercontent.com/33178835/156796309-f6f3a482-b46b-497c-b9b9-2ea34f0b47bd.mp4

---
Submission checklist: 

   

#### Layout
- [x] Change looks good in the desktop web ui
- [x] Change looks good in the mobile web ui

### CODE REVIEW

**Comment by asnaith** [comment]
The login screen is good but I'm seeing an issue with a scroll bar around the side-menu navigation after logging in

Screen Shot 2022-03-07 at 10 36 40 AM

**Review by asnaith — APPROVED** [review]
Looking good after the latest changes 👍

**Review by tanmoyAtb — APPROVED** [review]
looks good 👍

**Comment by Tbaut** [comment]
Thanks Mike for the fix :pray: Firefox didn't show this :)

**Pull request merged**
