### PR TITLE
Heic loader

### LINKED ISSUE #1635: Loader for HEIC conversion does not `spin`
The loader does not load while the HEIC conversion is in progress.

See video for sample:
https://user-images.githubusercontent.com/12774278/137383360-33537c63-01df-4ed4-aad3-a9a6b07c3cad.mov

_Originally posted by @asnaith in https://github.com/ChainSafe/ui-monorepo/issues/1618#issuecomment-942638894_

### PR DESCRIPTION
**Pull request by RyRy79261**
closes #1635

### CODE REVIEW

**Review by FSM1 — CHANGES_REQUESTED** [review]
There are now 2 spinner loader items rendering 👀 
image

**Comment by tanmoyAtb** [comment]
> There are now 2 spinner loader items rendering 👀 image

Spinner is working ok my side. I get one of them,
The spinners have a too dark color IMO, maybe use a `gray[8]`

**Review by tanmoyAtb — APPROVED** [review]
Looks good !

**Review by tanmoyAtb — DISMISSED** [review]
On second check, loaders are not appearing on normal screens, like the browsers.

**Review by FSM1 — CHANGES_REQUESTED** [review]
The HEIC loader works great now, as do all the other loaders, except for the file browser one.

PR Preview -
image


Current Staging - 
image

**Comment by RyRy79261** [comment]
@tanmoyAtb Unable to replicate as I only dev on a normal screen through a browser, where do you see the issue happening?

**Comment by FSM1** [comment]
> @tanmoyAtb Unable to replicate as I only dev on a normal screen through a browser, where do you see the issue happening?

@RyRy79261 this is present on all resolutions and all devices. The loader does not appear since these changes. See the screenshot I posted just above

**Comment by tanmoyAtb** [comment]
> @tanmoyAtb Unable to replicate as I only dev on a normal screen through a browser, where do you see the issue happening?

@RyRy79261 by browser I meant the file browsers. sorry the earlier message was a bit dubious.

**Comment by RyRy79261** [comment]
Unable to replicate issues on my side

**Comment by FSM1** [comment]
> Unable to replicate issues on my side

Light mode is now working perfectly on the file browser. The dark mode needs some color adjustment: 
image

**Review by FSM1 — APPROVED** [review]

**Review by asnaith — APPROVED** [review]

**Pull request merged**
