### PR TITLE
Settings back icon in mobile view

### LINKED ISSUE #1913: Clicking enabled on Settings header area
I noticed that I am currently able to click on the Settings header area and that it will take me back to the Profile and Display tab every time.

https://images.zenhubusercontent.com/285884697/2266d57b-0c3a-484b-8fee-96b4e90a077e/settings__button_.mov

Suggested solution: Make it not clickable

### PR DESCRIPTION
**Pull request by tanmoyAtb**
closes #1913 

---
Submission checklist: 

   

#### Layout
- [x] Change looks good in the desktop web ui
- [x] Change looks good in the mobile web ui

#### Theme
- [x] Components / elements inspected in light mode 
- [x] Components / elements inspected in dark mode

### CODE REVIEW

**Comment by asnaith** [comment]
Compared to Serena's mock on the issue ticket, it looks like the left arrow is only supposed to be shown when a tab has been opened and when on the main settings screen the header should be displayed as normal. 

At the moment the left arrow and smaller text is shown on the main settings screen too.  

Screen Shot 2022-02-14 at 12 27 36 PM

Also, could we make the left arrow itself a tappable target? At the moment it's only the text.

**Comment by tanmoyAtb** [comment]
> Compared to Serena's mock on the issue ticket, it looks like the left arrow is only supposed to be shown when a tab has been opened and when on the main settings screen the header should be displayed as normal.
> 
> At the moment the left arrow and smaller text is shown on the main settings screen too.
> 
> Screen Shot 2022-02-14 at 12 27 36 PM
> 
> Also, could we make the left arrow itself a tappable target? At the moment it's only the text.

Thanks for the pointers @asnaith. It looks better with the feedbacks in.

**Review by asnaith — APPROVED** [review]
@tanmoyAtb Looking great with the latest changes 🚀

**Review by Tbaut — APPROVED** [review]
:100:

**Pull request merged**
