### PR TITLE
Changed mobile click sensitivity

### LINKED ISSUE #1667: Difficulty scrolling past content (mobile)
When scrolling up or down content files, content gets selected upon scrolling gestures (too sensitive).

https://images.zenhubusercontent.com/285884697/b729f273-8f54-4517-b6ce-7b54c47c7713/sensitive_selection__scrolling_mobile_.mov

Is it possible to make selection less sensitive?

### LINKED ISSUE #1680: Overly Sensitive Content Preview (Mobile)
When previewing content (in this case, zooming in and out), the UI is so sensitive that the content keeps changing and reloading.

https://images.zenhubusercontent.com/285884697/fe707743-ebf0-45a6-9102-97e3ae20487c/sensitive_content_preview__landscape_.mp4

### LINKED ISSUE #1682: Overly Sensitive File Selection (Mobile)
Content selection is very sensitive-- it is difficult scrolling up and down without selecting content along the way.

https://images.zenhubusercontent.com/285884697/3dc15153-0ceb-4f4b-bfb7-2960d9c40704/sensitive_file_selection__mobile_.mp4

### PR DESCRIPTION
**Pull request by RyRy79261**
closes #1682 
closes #1680 
closes #1667

### CODE REVIEW

**Comment by Tbaut** [comment]
Tested on Chrome on Android (real device) and I couldn't select several files and couldn't do a quick touch to open a file either 🤔

**Comment by tanmoyAtb** [comment]
> Tested on Chrome on Android (real device) and I couldn't select several files and couldn't do a quick touch to open a file either 🤔

I just checked on an android Chrome  browser. Working well for me. Can you check again? 
And are you checking the preview or local build ?

**Review by FSM1 — APPROVED** [review]
Seems to be working well on my side, tested on device.

**Review by Tbaut — APPROVED** [review]
All these `any` make me :cry: but on events I'll close my eyes, I know it can be pretty annoying for no great benefit.

Not sure what I tried before (was the render) but it looks good now :100:

**Comment by Tbaut** [comment]
I won't merge to let @asnaith play with it on iphone.

**Comment by tanmoyAtb** [comment]
> All these `any` make me 😢 but on events I'll close my eyes, I know it can be pretty annoying for no great benefit.
> 
> Not sure what I tried before (was the render) but it looks good now 💯

I know, didn't like putting in all those `any` either, deriving all the event types was getting really messy :(.

**Review by asnaith — APPROVED** [review]
Nice changes @RyRy79261 and @tanmoyAtb. This is a great improvement on iOS.

**Comment by serenaho** [comment]
Just checked and it works well on my device too. Great job :)

**Comment by RyRy79261** [comment]
@asnaith I just tinkered, @tanmoyAtb lead the charge here 🔥

**Pull request merged**
