### PR TITLE
Upload files sequentially by path

### LINKED ISSUE #2098: [Files] Significant number of directories and files missing after upload.
**Describe the bug**
While attempting to upload a directory with a large number of sub-directories, which in turn have sub-sub-directories, etc., the files fail to upload, with a sizeable chunk of them missing.

**To Reproduce**
1. Create a directory `Test`.
2. In the `Test` directory, create 3 sub-directories named `A`, `B`, and `C`.
3. To the `Test` directory, add 3 text files called `a.txt`, `b.txt`, and `c.txt`.
4. To the `A`, `B` and `C` directories, add 3 text files `a.txt`, `b.txt` and `c.txt`.
5. Drag the `Test` directory over to Files.

**Expected behavior**
The file structure of the `Test` directory should look as follows:
```markdown
- Test/
  - A/
    - a.txt
    - b.txt
    - c.txt
  - B/
    - a.txt
    - b.txt
    - c.txt
  - C/
    - a.txt
    - b.txt
    - c.txt
  - a.txt
  - b.txt
  - c.txt    
```

**Observed behavior**
The file structure of the `Test` directory after uploading looks as follows:
```markdown
- Test/
  - A/
    - a.txt
    - b.txt
    - c.txt
  - B/
    - a.txt
    - b.txt
    - c.txt
``` 

**Screenshots**
Animation

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 99.0.1

### PR DESCRIPTION
**Pull request by Tbaut**
closes #2098 

The UX isn't awesome. but it will be worked on here https://github.com/ChainSafe/ui-monorepo/issues/2097

https://user-images.githubusercontent.com/33178835/164195945-1de0aba8-e8c1-466c-a68d-520b921c1660.mp4

### CODE REVIEW

**Comment by Tbaut** [comment]
ok it should be good to go :)

**Review by asnaith — APPROVED** [review]
Network throttling makes this easier to test 😄🙏

👍 I can see it uploading sequentially based on the order I see on the dialog:

Screen Shot 2022-04-25 at 3 46 01 PM

It doesn't make sense to me how it uploads folder C before folder B but I think it's fine to merge because there's an upload manager mentioned in https://github.com/ChainSafe/ui-monorepo/issues/2097 and the upload order behaviour can be finalized in that change.

**Comment by juans-chainsafe** [comment]
Working as expected! I found this related issue while testing this: https://github.com/ChainSafe/ui-monorepo/issues/2112

**Review by FSM1 — APPROVED** [review]
lgtm

**Pull request merged**
